---
name: Build Image

on:
  push:
    branches: ['*']

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build Image
        id: build-image
        run: docker build . --file Dockerfile.arm64 --tag test-eguz-arm64:$(date +%s)
